// Static directory data served by the GET endpoints (/api/competitors,
// /api/communities, /api/influencers). Kept server-side so the same data can later
// be swapped for a live source (App Store scrape, Reddit API, creator DB) without
// touching the frontend contract.

export const competitors = [
  {
    name: "Habitify",
    emoji: "✅",
    rating: 4.7,
    downloads: "1.2M",
    pricing: "Freemium",
    strengths: ["Clean UX", "Cross-device sync", "Rich charts"],
    weaknesses: ["Weak community", "Overwhelming for beginners"],
    channels: ["App Store", "Reddit", "Product Hunt"],
    keywords: ["habit tracker", "daily routine", "productivity"],
    complaint: '"Way too many settings — I just want to check off my morning walk."',
  },
  {
    name: "Streaks",
    emoji: "🔥",
    rating: 4.8,
    downloads: "800K",
    pricing: "Paid ($4.99)",
    strengths: ["Beautiful design", "Apple Watch", "Loyal fanbase"],
    weaknesses: ["iOS only", "No social features", "Rigid streak logic"],
    channels: ["App Store Features", "Twitter"],
    keywords: ["streak", "iOS habit", "minimal"],
    complaint: '"One missed day and my 200-day streak is gone. Brutal."',
  },
  {
    name: "Way of Life",
    emoji: "📅",
    rating: 4.4,
    downloads: "600K",
    pricing: "Freemium",
    strengths: ["Long history", "Simple color grid", "Export data"],
    weaknesses: ["Dated UI", "Slow updates", "Poor onboarding"],
    channels: ["App Store", "Blogs"],
    keywords: ["color chart", "habit journal"],
    complaint: '"Looks like it was designed in 2013 because it was."',
  },
  {
    name: "Fabulous",
    emoji: "🌅",
    rating: 4.6,
    downloads: "10M+",
    pricing: "Subscription ($9.99/mo)",
    strengths: ["Coach-driven content", "Big brand", "Guided routines"],
    weaknesses: ["Expensive", "Aggressive paywall", "Feels bloated"],
    channels: ["TikTok", "YouTube ads", "Instagram"],
    keywords: ["morning routine", "wellness coach"],
    complaint: '"Free trial forced me into a $80/year plan I didn\'t want."',
  },
  {
    name: "Done",
    emoji: "🎯",
    rating: 4.5,
    downloads: "300K",
    pricing: "Freemium",
    strengths: ["Fast to add habits", "Nice widgets"],
    weaknesses: ["Basic analytics", "No web app"],
    channels: ["App Store", "Reddit"],
    keywords: ["habit widget", "iOS"],
    complaint: '"Wish it had weekly reports without upgrading."',
  },
  {
    name: "Productive",
    emoji: "⚡",
    rating: 4.6,
    downloads: "2M",
    pricing: "Subscription ($6.99/mo)",
    strengths: ["Rituals grouping", "Solid stats", "Widgets"],
    weaknesses: ["Sub pressure", "Confusing plans"],
    channels: ["App Store", "Instagram"],
    keywords: ["rituals", "daily planner"],
    complaint: '"Every third tap opens the upgrade screen."',
  },
];

export const communities = [
  {
    name: "r/getdisciplined",
    platform: "Reddit",
    size: "1.4M members",
    best: "Tue–Thu, 9am PST",
    rules: "No self-promo without value. Story format works.",
    difficulty: 3,
    traffic: "High",
    cta: "Draft founder story",
  },
  {
    name: "Indie Hackers",
    platform: "Indie Hackers",
    size: "180K makers",
    best: "Weekdays, 8am EST",
    rules: "Milestones + revenue transparency get traction.",
    difficulty: 2,
    traffic: "Medium",
    cta: "Draft milestone post",
  },
  {
    name: "Product Hunt",
    platform: "Product Hunt",
    size: "5M visitors/mo",
    best: "Tuesday 12:01 PST",
    rules: "One shot per product. Hunters matter.",
    difficulty: 4,
    traffic: "High",
    cta: "Draft launch copy",
  },
  {
    name: "Hacker News",
    platform: "Hacker News",
    size: "5M readers",
    best: "Weekday mornings PST",
    rules: "Show HN posts only. Technical honesty wins.",
    difficulty: 5,
    traffic: "High",
    cta: "Draft Show HN",
  },
  {
    name: "r/productivity",
    platform: "Reddit",
    size: "2.1M members",
    best: "Sun–Mon evenings",
    rules: "Discuss method, not product. Link in comments.",
    difficulty: 3,
    traffic: "Medium",
    cta: "Draft discussion",
  },
  {
    name: "Designer Hangout",
    platform: "Discord",
    size: "45K designers",
    best: "Weekdays, all day",
    rules: "Introduce yourself. Share process, not pitch.",
    difficulty: 2,
    traffic: "Low",
    cta: "Draft intro",
  },
];

export const influencers = [
  {
    name: "Maya Okafor",
    handle: "@mayabuilds",
    platform: "Instagram",
    followers: "38.2K",
    engagement: "6.4%",
    installs: "420–620",
    price: "$650",
    match: 92,
    tags: ["habits", "wellness", "solo founders"],
  },
  {
    name: "Devon Park",
    handle: "@devonpark",
    platform: "TikTok",
    followers: "112K",
    engagement: "8.1%",
    installs: "1.1K–1.6K",
    price: "$1,400",
    match: 88,
    tags: ["productivity", "gen-z", "morning routines"],
  },
  {
    name: "Rina Patel",
    handle: "@rina.reads",
    platform: "Instagram",
    followers: "22.5K",
    engagement: "5.9%",
    installs: "280–410",
    price: "$400",
    match: 84,
    tags: ["mindfulness", "journaling"],
  },
  {
    name: "Alex Thorne",
    handle: "@alexbuildsapps",
    platform: "Twitter",
    followers: "48K",
    engagement: "3.2%",
    installs: "180–260",
    price: "$250",
    match: 79,
    tags: ["indie dev", "launch", "iOS"],
  },
  {
    name: "Sana Ito",
    handle: "@sanaito",
    platform: "TikTok",
    followers: "215K",
    engagement: "9.4%",
    installs: "1.8K–2.4K",
    price: "$2,100",
    match: 76,
    tags: ["study", "aesthetic", "planner"],
  },
  {
    name: "Jordan Ellis",
    handle: "@jordanellis",
    platform: "YouTube",
    followers: "84K",
    engagement: "5.0%",
    installs: "600–900",
    price: "$1,800",
    match: 73,
    tags: ["deep work", "long-form"],
  },
];
