// functions/api/communities.ts
import { corsHeaders, handleOptions } from "./utils";

export const onRequestOptions = handleOptions;

export const onRequestGet: PagesFunction = async () => {
  try {
    const communities = [
      {
        name: "r/getdisciplined",
        platform: "Reddit",
        size: "1.4M members",
        dau: "95K active/day",
        growthTrend: "+5.2% WoW",
        opportunityScore: 94,
        expectedDownloads: 350,
        aiConfidence: 92,
        recommendedFrequency: "Bi-weekly",
        contentType: "Founder Story",
        best: "9am PST",
        bestDay: "Tuesday",
        activityTrend: "Increasing (+5%)",
        successfulPostExample: "\"How I broke the 100-day habit shame loop (without streaks)\"",
        commonMistake: "Directly linking to the App Store in the post body instead of commenting.",
        restrictions: "Self-promo must include highly detailed methodologies.",
        sentiment: "Positive (84%)",
        aiSummary: "High-value self-improvement forum. Empathy-focused founder stories explaining user habits get optimal upvotes.",
        difficulty: 3,
        traffic: "High",
        cta: "Draft founder story",
        description: "A community focused on self-improvement, routines, and building personal discipline.",
        category: "Health & Fitness"
      },
      {
        name: "Indie Hackers",
        platform: "Indie Hackers",
        size: "180K makers",
        dau: "18K active/day",
        growthTrend: "+2.1% WoW",
        opportunityScore: 88,
        expectedDownloads: 150,
        aiConfidence: 86,
        recommendedFrequency: "Weekly",
        contentType: "Milestone Update",
        best: "8am EST",
        bestDay: "Monday",
        activityTrend: "Steady (+2%)",
        successfulPostExample: "\"Building a calm habit tracker: reached $250 MRR in 14 days\"",
        commonMistake: "Failing to detail marketing metrics and lessons learned.",
        restrictions: "Must be related to startup or indie making details.",
        sentiment: "Highly Positive (92%)",
        aiSummary: "Maker-focused community. Share growth loops, ASO tweaks, and milestones to acquire initial early adopter users.",
        difficulty: 2,
        traffic: "Medium",
        cta: "Draft milestone post",
        description: "Community of indie software creators and digital makers sharing transparency updates.",
        category: "Productivity"
      },
      {
        name: "Product Hunt",
        platform: "Product Hunt",
        size: "5M visitors/mo",
        dau: "120K active/day",
        growthTrend: "+12.4% WoW",
        opportunityScore: 97,
        expectedDownloads: 850,
        aiConfidence: 95,
        recommendedFrequency: "Once",
        contentType: "Launch Post",
        best: "12:01 PST",
        bestDay: "Tuesday",
        activityTrend: "Highly Active (+12%)",
        successfulPostExample: "\"Fernly — Break the shame loop of habit tracking\"",
        commonMistake: "Launching without warm upvotes, an active hunter, or a first-comment promo link.",
        restrictions: "One launch submission per product per six months.",
        sentiment: "Neutral-Positive (78%)",
        aiSummary: "The ultimate launchpad. High conversion potential. Requires clean media, catchy tagline, and warm hunter support.",
        difficulty: 4,
        traffic: "High",
        cta: "Draft launch copy",
        description: "The primary global launchpad for new digital products, software tools, and mobile apps.",
        category: "General"
      },
      {
        name: "Hacker News",
        platform: "Hacker News",
        size: "5M readers",
        dau: "650K active/day",
        growthTrend: "+4.8% WoW",
        opportunityScore: 78,
        expectedDownloads: 450,
        aiConfidence: 74,
        recommendedFrequency: "Once",
        contentType: "Show HN",
        best: "8am PST",
        bestDay: "Wednesday",
        activityTrend: "Fluctuating (-1%)",
        successfulPostExample: "\"Show HN: A habit tracker designed around forgiveness, not streaks\"",
        commonMistake: "Overly salesy titles, aggressive monetization, or blocking user comments.",
        restrictions: "Must follow Show HN guidelines explicitly.",
        sentiment: "Critical-Neutral (62%)",
        aiSummary: "High intellectual density. Explaining the science of habit-loops and keeping monetization humble is mandatory.",
        difficulty: 5,
        traffic: "High",
        cta: "Draft Show HN",
        description: "A highly technical aggregator focused on computer science, start-ups, and technology.",
        category: "Productivity"
      },
      {
        name: "r/productivity",
        platform: "Reddit",
        size: "2.1M members",
        dau: "140K active/day",
        growthTrend: "+6.5% WoW",
        opportunityScore: 92,
        expectedDownloads: 280,
        aiConfidence: 89,
        recommendedFrequency: "Weekly",
        contentType: "Problem Discussion",
        best: "6pm PST",
        bestDay: "Sunday",
        activityTrend: "Increasing (+6%)",
        successfulPostExample: "\"Why streak apps make us quit habits (and how I fixed it)\"",
        commonMistake: "Spamming link redirects without engaging in the thread comments.",
        restrictions: "Links must fit context; strict anti-spam filters.",
        sentiment: "Positive (80%)",
        aiSummary: "Primary target. Users discuss workflow optimizations. Frame posts around routine theories and share designs.",
        difficulty: 3,
        traffic: "Medium",
        cta: "Draft discussion",
        description: "A forum dedicated to productivity tips, frameworks, habit building, and application structures.",
        category: "Productivity"
      },
      {
        name: "r/personalfinance",
        platform: "Reddit",
        size: "18M members",
        dau: "450K active/day",
        growthTrend: "+1.2% WoW",
        opportunityScore: 84,
        expectedDownloads: 190,
        aiConfidence: 80,
        recommendedFrequency: "Weekly",
        contentType: "Strategy Comment",
        best: "8am EST",
        bestDay: "Monday",
        activityTrend: "Steady (+1%)",
        successfulPostExample: "\"Budget planning framework that saved me $400/mo\"",
        commonMistake: "Promoting paid plans directly. Target free spreadsheets or simple utilities.",
        restrictions: "Strictly commercial links are banned.",
        sentiment: "Neutral (70%)",
        aiSummary: "Large finance community. Focus on expense tracking strategies and share budgeting layouts.",
        difficulty: 4,
        traffic: "High",
        cta: "Draft finance advice",
        description: "Budget planning, saving methodologies, and expense tracking discussion forum.",
        category: "Finance"
      },
      {
        name: "r/travel",
        platform: "Reddit",
        size: "8.5M members",
        dau: "180K active/day",
        growthTrend: "+3.9% WoW",
        opportunityScore: 86,
        expectedDownloads: 220,
        aiConfidence: 83,
        recommendedFrequency: "Bi-weekly",
        contentType: "Route Recommendation",
        best: "5pm PST",
        bestDay: "Thursday",
        activityTrend: "Increasing (+4%)",
        successfulPostExample: "\"My offline hiking itinerary for Yosemite backcountry routes\"",
        commonMistake: "Sharing low resolution pictures or generic travel lists.",
        restrictions: "Posts must feature specific itineraries or photos.",
        sentiment: "Positive (86%)",
        aiSummary: "Visual travel community. High interest in offline maps, GPS coordinate logging, and backpacking trails.",
        difficulty: 2,
        traffic: "Medium",
        cta: "Draft travel post",
        description: "Global community sharing itineraries, hiking routes, maps, and travel recommendations.",
        category: "Travel"
      }
    ];

    return new Response(JSON.stringify(communities), {
      status: 200,
      headers: corsHeaders()
    });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: corsHeaders()
    });
  }
};
