/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as StudioTypeRouteImport } from './routes/studio.$type'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const StudioTypeRoute = StudioTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => StudioRoute,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/onboarding': typeof OnboardingRoute
  '/strategy': typeof StrategyRoute
  '/studio': typeof StudioRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/studio/$type': typeof StudioTypeRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/discover': typeof DiscoverRoute
  '/onboarding': typeof OnboardingRoute
  '/strategy': typeof StrategyRoute
  '/studio': typeof StudioRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/studio/$type': typeof StudioTypeRoute
  '/campaigns': typeof CampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/onboarding': typeof OnboardingRoute
  '/strategy': typeof StrategyRoute
  '/studio': typeof StudioRouteWithChildren
  '/campaigns/new': typeof CampaignsNewRoute
  '/studio/$type': typeof StudioTypeRoute
  '/campaigns/': typeof CampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/discover'
    | '/onboarding'
    | '/strategy'
    | '/studio'
    | '/campaigns/new'
    | '/studio/$type'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/discover'
    | '/onboarding'
    | '/strategy'
    | '/studio'
    | '/campaigns/new'
    | '/studio/$type'
    | '/campaigns'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/discover'
    | '/onboarding'
    | '/strategy'
    | '/studio'
    | '/campaigns/new'
    | '/studio/$type'
    | '/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  OnboardingRoute: typeof OnboardingRoute
  StrategyRoute: typeof StrategyRoute
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/studio/$type': {
      id: '/studio/$type'
      path: '/$type'
      fullPath: '/studio/$type'
      preLoaderRoute: typeof StudioTypeRouteImport
      parentRoute: typeof StudioRoute
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface StudioRouteChildren {
  StudioTypeRoute: typeof StudioTypeRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioTypeRoute: StudioTypeRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  OnboardingRoute: OnboardingRoute,
  StrategyRoute: StrategyRoute,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
